[package]
name = "day-24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
num = "0.4.1"
z3 = { version = "0.12.1", features = ["num", "static-link-z3"] }
